MVCSelection/Models/DogViewModel.cs
namespace MVCSelection.Models
{
    public class DogViewModel
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

MVCSelection/Models/ErrorViewModel.cs
namespace MVCSelection.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCSelection/Controllers/GreetingController.cs
using Microsoft.AspNetCore.Mvc;
using MVCSelection.Models;

namespace MVCSelection.Controllers
{
    public class GreetingController : Controller
    {
        public IActionResult Index()
        {
            DogViewModel dog = new DogViewModel() { Name = "Zambie", Age = 8 };
            return View(dog);
        }

        public IActionResult Create()
        {
            var dogVm = new DogViewModel();
            return View(dogVm);
        }

        public IActionResult CreateDog(DogViewModel dogViewModel)
        {
            return View("Index");
        }
        public string Hello()
        {
            return "Who is there?";
        }
    }

}

MVCSelection/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCSelection.Models;
using System.Diagnostics;

namespace MVCSelection.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCSelection/Views/Greeting/Create.cshtml
@model DogViewModel
@*^^Model added must match what was passed as an argument from Create()
method in GreetingController*@

<h1>Create check</h1>
<hr />
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h5>Create a new Dog</h5>
            </div>
            <div class="card-body">
                <form asp-controller="Greeting"> 
                    @*asp-controller must match prefix of relevant
                        controller
                    *@
                    <div class="mb-3">
                        <label class="form-label">Dog Name</label>
                        <input type="text" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Dog Age</label>
                        <input type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-primary">Save Dog</button>
                    </div>
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>

    </div>
</div>

MVCSelection/Views/Greeting/Index.cshtml
@model MVCSelection.Models.DogViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Hello Test</h1>
<p>Welcome to our hello test site</p>
<h4>My dog is named @Model.Name</h4>
<h4>@Model.Name 's age is @Model.Age</h4>

MVCSelection/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCSelection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCSelection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCSelection.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Greeting" asp-action="Index">DogApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Greeting" asp-action="Index">Dog List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Greeting" asp-action="Create">Create Dog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCSelection - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>